# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 抖音火山

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */6 * * *'
  watch:
    types: started
  repository_dispatch:
    types: hotsoon
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
          HSURL: ${{ secrets.HSURL }}
          HSHEADER: ${{ secrets.HSHEADER }}
          HSBODY: ${{ secrets.HSBODY }}
          PLAYURL: ${{ secrets.PLAYURL }}
          PLAYHEADER: ${{ secrets.PLAYHEADER }}
          PLAYBODY: ${{ secrets.PLAYBODY }}
    steps:
      - name: Checkout
        run: |	
          git clone https://github.com/wsdjj/TaskAction.git ~/TaskAction
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
         with:
          node-version: 12.x
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
         - name: npm install
        if: env.YOUTH_HEADER
        run: |
        
          
          npm install
      - name: '运行 【火山】'
        run: |
          cd ~/TaskAction/workflow
          node huoshan.js
        env:
          HSURL: ${{ secrets.HSURL }}
          HSHEADER: ${{ secrets.HSHEADER }}
          HSBODY: ${{ secrets.HSBODY }}
          PLAYURL: ${{ secrets.PLAYURL }}
          PLAYHEADER: ${{ secrets.PLAYHEADER }}
          PLAYBODY: ${{ secrets.PLAYBODY }}
